<?php

/**
 * PluginTinyCmsContentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTinyCmsContentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTinyCmsContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTinyCmsContent');
    }
}