<?php

/**
 * PluginTinyCmsPageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTinyCmsPageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTinyCmsPageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTinyCmsPage');
    }
}