all:
  tinycms:
    security:
      edit:
        # Tells whether only authenticated users can edit content or not
        authenticated:                    true

        # Tells whether only users with the given credential(s) can edit content or not
        # ~ for no specific credentials, a table for several allowed credentials (e.g. [admin, writer]), string for only one
        credentials:                      [[editor,admin]]

